"""Import Data page."""
import streamlit as st
import pandas as pd
from app.database import WorkflowDB, InstanceDB
import json
from datetime import datetime, timedelta

def render_import_page(user_id: str):
    """Renders the Import Data page."""
    st.title("📥 Import Data")
    
    st.markdown("""
    ### ℹ️ How to use this feature
    This feature allows you to import observation data that was previously exported from this application. 
    It is useful for merging data from multiple users, restoring backups, or combining data from different devices into a single workflow for comprehensive analysis.
    
    **Requirements:**
    1. The file must be an Excel file (`.xlsx`) generated by the "Export to Excel" button on the Reporting page.
    2. The columns should remain unmodified (Instance Name, Notes, Start Time, Completion Time, Total Duration, and step duration columns).
    """)
    
    st.markdown("---")
    
    uploaded_file = st.file_uploader("Choose an exported Excel file", type=['xlsx'])
    
    if uploaded_file is not None:
        try:
            df = pd.read_excel(uploaded_file)
            
            # Validation
            required_cols = ["Instance Name", "Notes", "Start Time", "Completion Time", "Total Duration"]
            missing_cols = [col for col in required_cols if col not in df.columns]
            
            if missing_cols:
                st.error(f"❌ Invalid file format. Missing required columns: {', '.join(missing_cols)}")
                return
                
            step_duration_cols = [col for col in df.columns if '(duration)' in col and 'Total' not in col]
            
            if not step_duration_cols:
                st.error("❌ Invalid file format. No step duration columns found.")
                return
                
            st.success(f"✅ File validated successfully! Found {len(df)} instances and {len(step_duration_cols)} steps.")
            
            # Select workflow
            workflows = WorkflowDB.get_workflows(user_id)
            if not workflows:
                st.warning("No workflows found. Please create a workflow on the Workflows page first.")
                return
                
            workflow_map = {wf["name"]: wf for wf in workflows}
            selected_workflow_name = st.selectbox("Select target workflow for the imported data:", options=list(workflow_map.keys()))
            
            selected_workflow = workflow_map[selected_workflow_name]
            workflow_steps = selected_workflow.get("steps", [])
            
            if len(workflow_steps) != len(step_duration_cols):
                st.warning(f"⚠️ Warning: The selected workflow has {len(workflow_steps)} steps, but the imported file has {len(step_duration_cols)} step durations. It is highly recommended to import into a workflow with matching steps.")
            
            # Confirmation
            st.warning("⚠️ **Warning:** Importing data is unreversible. Please confirm that you want to add this data to the selected workflow.")
            
            confirm = st.checkbox("I understand that this action cannot be undone.")
            
            if st.button("Import Data", type="primary", disabled=not confirm):
                with st.spinner("Importing data..."):
                    instances_to_import = []
                    
                    for _, row in df.iterrows():
                        instance_name = str(row["Instance Name"]) if pd.notna(row["Instance Name"]) else "Imported Instance"
                        notes = str(row["Notes"]) if pd.notna(row["Notes"]) and str(row["Notes"]).lower() != "nan" else ""
                        
                        start_time_str = row["Start Time"]
                        started_at = None
                        current_time = None
                        
                        if pd.notna(start_time_str) and start_time_str != "N/A":
                            try:
                                started_dt = pd.to_datetime(start_time_str)
                                started_at = started_dt.isoformat()
                                current_time = started_dt
                            except:
                                started_at = datetime.now().isoformat()
                                current_time = datetime.now()
                        else:
                            started_at = datetime.now().isoformat()
                            current_time = datetime.now()
                            
                        timestamps = []
                        total_steps_completed = 0
                        
                        for i, col in enumerate(step_duration_cols):
                            duration_str = row[col]
                            if pd.notna(duration_str) and duration_str != "N/A":
                                try:
                                    h, m, s = map(int, str(duration_str).split(':'))
                                    duration_sec = h * 3600 + m * 60 + s
                                    current_time += timedelta(seconds=duration_sec)
                                    timestamps.append({
                                        "step": i,
                                        "timestamp": current_time.isoformat()
                                    })
                                    total_steps_completed += 1
                                except:
                                    pass
                        
                        completion_time_str = row["Completion Time"]
                        if pd.notna(completion_time_str) and completion_time_str != "N/A":
                            try:
                                completion_dt = pd.to_datetime(completion_time_str)
                                timestamps.append({
                                    "step": -1,
                                    "timestamp": completion_dt.isoformat()
                                })
                            except:
                                timestamps.append({
                                    "step": -1,
                                    "timestamp": current_time.isoformat()
                                })
                        else:
                            timestamps.append({
                                "step": -1,
                                "timestamp": current_time.isoformat()
                            })
                                
                        instances_to_import.append({
                            "name": instance_name,
                            "notes": notes,
                            "started_at": started_at,
                            "timestamps": timestamps,
                            "current_step": len(workflow_steps)
                        })
                    
                    try:
                        success = InstanceDB.import_instances(selected_workflow["id"], instances_to_import, user_id)
                        if success:
                            st.success(f"🎉 Successfully imported {len(instances_to_import)} instances to '{selected_workflow_name}'!")
                        else:
                            st.error("❌ Failed to import instances. Please check your database connection.")
                    except Exception as db_err:
                        st.error(f"❌ Database error: {str(db_err)}")
                        
        except Exception as e:
            st.error(f"❌ Error processing file: {str(e)}")