"""User Guide page for instructions and documentation."""
import streamlit as st

def render_user_guide_page(user_id: str):
    """Renders the User Guide page."""
    st.title("📖 User Guide")
    
    st.markdown("""
    Welcome to **Temporiq AI**, a clinical operations observation tool designed to track patient workflows in real-time, log timestamps, and visualize progress.

    Here is a comprehensive guide on everything this application can do:

    ### ⚙️ Workflows
    The Workflows page is where you configure the steps for your clinical observations.
    - **Create New Workflow:** Enter a name and select the number of steps (2-10). Name each step to match your specific clinical process (e.g., "Check-in", "Triage", "Consult").
    - **Manage Workflows:** Edit existing workflows or delete them if no longer needed. Note that deleting a workflow also deletes all its associated tracked instances.
    - **Start Tracking:** Click the play button (▶️) on a workflow to select it and head straight to the Tracker.

    ### ⏱️ Tracker
    The Tracker is your active dashboard for live observations.
    - **Add an Instance:** Enter an identifier (like a patient ID or room number) and click "Add". You can also toggle "Auto-start on add" to begin tracking immediately.
    - **Track Progress:** As the subject completes each step, click the corresponding step button to log the timestamp.
    - **Active & Completed:** Instances automatically move from "Active" to "Completed" once all steps are checked off.
    - **Notes & Timeline:** Expand the "Notes" section of any card to jot down qualitative observations. The "Step Timeline" shows exactly how long each phase took.

    ### 📈 Reporting
    Analyze your collected data to identify bottlenecks and optimize operations.
    - **View Data:** Select a workflow and filter by date range to see a tabular summary of total and per-step durations.
    - **Export to Excel:** Download your data as an `.xlsx` file for external analysis or sharing.
    - **Visual Analysis:** Review auto-generated charts showing the average time spent per step and cumulative durations per instance.
    - **🤖 AI-Powered Analysis:** Use the Gemini AI integration to generate an intelligent summary of your workflow's performance, highlighting potential bottlenecks and actionable recommendations. You can even export this analysis to Markdown.

    ### 📥 Import Data
    Seamlessly bring external or previously exported data back into the app.
    - **Supported Format:** You can upload `.xlsx` files generated by the app's Reporting page.
    - **Validation:** The system automatically checks for required columns to ensure data integrity.
    - **Merging:** This is especially useful for merging data tracked by different users on different devices into a single, unified workflow.

    ---
    *Tip: Use the sidebar on the left to navigate between these pages. You can collapse the sidebar for a distraction-free tracking experience.*
    """)
    
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("Get Started (Go to Workflows)", type="primary"):
        st.session_state.current_page = "Workflows"
        st.rerun()